# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-24 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='movieList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('vote_count', models.IntegerField()),
                ('vote_average', models.IntegerField()),
                ('poster_path', models.URLField()),
                ('logo_path', models.URLField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
